todos:
- title: Exception Insee.pm
  description: Ajout d'une classe d'exception et utilisation dans Insee.pm
  marked: false
  id: 0
- title: Traitement des bases de données
  description: Voir les fichiers de l'INSEE pour les mettre en version Minimum (SIREN,
    SIRET,Adresse)
  marked: false
  id: 0
- title: Voir Comment traiter les update
  description: Faire un fichier de creation et un de suppression
  marked: false
  id: 0
- title: 'Méthode format : quand regex = null'
  description: Faire un traitement afin de traiter le cas ou l'on souhaite tout prendre
  marked: false
  id: 0
- title: Faire une application
  description: Pour pouvoir montrer quelque chose
  marked: false
  id: 0
- title: Faire mapping
  description: Faire le mapping pour les valeurs sap
  marked: false
  id: 0
- title: Format de sortie
  description: faire un format JSON et un format XML plus tard voir pour un format
    csv ou tab separated
  marked: false
  id: 0
