requires 'Modern::Perl';
requires 'Mojolicious' ;
requires 'Moose';
requires 'Business::Tax::VAT::Validation';
requires 'DBI';
requires 'DBD::Pg';
requires 'MongoDB';
requires 'Exception::Class';
requires 'Throwable';
requires 'Try::Tiny';
requires 'Cpanel::JSON::XS';
