requires 'Moose';
requires 'Exception::Class';
requires 'Throwable';
requires 'Devel::Peek';
requires 'Cpanel::JSON::XS';
requires 'Mojo::IOLoop::ReadWriteFork';
requires 'Business::Tax::VAT::Validation';
requires 'URI::Escape';
requires 'Role::REST::Client';
