requires 'Modern::Perl';
requires 'Mojolicious' ;
requires 'Mojolicious::Lite';
requires 'Moose';
requires 'Business::Tax::VAT::Validation';
requires 'DBI';
requires 'Exception::Class';
requires 'Throwable';
requires 'Try::Tiny';
requires 'Cpanel::JSON::XS';
requires 'Mojolicious::Plugin::JSON::XS';
requires 'Mojo::IOLoop::ReadWriteFork';
requires 'Role::REST::Client';
requires 'URI::Escape';
